### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-connector-couchbase3#1]
To achieve that, we need:

- [x] CRUD methods (https://github.com/strongloop/loopback-datasource-juggler/blob/master/docs/datasource-connector.md)
- [x] Better tests
- [x] Better readme

@Wiredcraft/core-members @Wiredcraft/applicants Any help would be appreciated. Please send me pull requests if you are willing to help.

**Comment by makara** [comment]
Hi @CCharlieLi I need this in a week. Do you think you can get it done?

**Comment by CCharlieLi** [comment]
Ok! I was looking at the source code these days, I'll try my best!

**Comment by makara** [comment]
Thanks. And please:

- Track your time
- Let me know your schedule
- Show your progress frequently (commit or comment or whatever)

**Comment by CCharlieLi** [comment]
### Schedule
- Tus
      - Deploy Couchbase and this app, run test and get familiar with these code. 
- Wed & Thu
      - Deploy CRUD methods.
- Fri & Sat
      - Deploy tests and fix bug.

I have already forked this repo and got this run at localhost, it takes me some time to learn about the Couchbase and loopback-connector, and I will commit when I have more progress.

**Comment by makara** [comment]
Thanks. Closing.
