### ISSUE TITLE
The  _cas will be changed to other value if there is a field name _cas  in db

### ISSUE THREAD

**Issue by superbogy** [Wiredcraft/loopback-connector-couchbase3#107]
https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/6d79f64b09e85dc1449e031c05d120dae0f6cd1f/lib/utils.js#L55
I got a string type `_cas ` when I run test.I found that there is a record with `_cas` field in db.
After debugging I guess the package `loopback-connector-nosql` do that.

https://github.com/Wiredcraft/loopback-connector-nosql/blob/0c3ad3c35b691f4ff2af4671f2dc43abf68ecc97/lib/nosql.js#L226

`Object.assign(res, data)` will auto add `_cas` to update payload.
@xavierchow @makara @CCharlieLi

**Comment by xavierchow** [comment]
Good catch, I think we can trim the `_cas` from the payload if we see it as a meta of the document.

BTW, the reduce here is verbose, `.length` should be good enough.
https://github.com/Wiredcraft/loopback-connector-nosql/blob/0c3ad3c35b691f4ff2af4671f2dc43abf68ecc97/lib/nosql.js#L227-L229

**Comment by xavierchow** [comment]
Wait, what is the use case of `update` with a single payload, i.e. find all documents matching the `where clause` then update them with the same payload?

**Comment by xavierchow** [comment]
Landed in v1.2.0 :shipit:
