### ISSUE TITLE
how about give every module a type attribute default value is module name

### ISSUE THREAD

**Issue by ChopperLee2011** [Wiredcraft/loopback-connector-couchbase3#11]
About the `Remember to create a “type” attribute that will help you differentiate the various objects stored in the bucket and create indexes on them. `  I kind of agree that as a couchbase best practice, so why not set it as a default feature in this connector or maybe a configure, and we can use the module name as the `type`.

**Comment by makara** [comment]
Can we build that as a mixin?

How do you index things BTW? Do we need to create views?

**Comment by ChopperLee2011** [comment]
i always thought mixin is anti-pattern, so maybe it is a reason to change the lib with es6 syntax `extend`, but  it is not necessary.
hell i can not figure it out if do the index part:
- add `create index` on the connector;
- index will not works good when data re-import much times;
- the prof, slow the `create` and 'find' time

**Comment by makara** [comment]
You mean anti-OO probably. See https://github.com/clarkbw/loopback-ds-timestamp-mixin/blob/master/es6/time-stamp.js. Isn't that much more flexible than extending? Either way we are not forcing the best practice so user should be able to enable/disable it.

Also I think we usually put different types in different buckets and I doubt saving a `type` is any better.

We can talk about the index later.

**Comment by ChopperLee2011** [comment]
done, thanks @makara
