### ISSUE TITLE
Changelog automation

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-connector-couchbase3#112]
The `History.md` is not automatically updated when bumping up versions,
@superbogy pls help to set up automatic changelog updating with https://github.com/Wiredcraft/api-boilerplate#how-to-create-changelog.

**Comment by superbogy** [comment]
@xavierchow I would like to add a new file `CHANGELOG.md` with the `conventional-changelog` version script. Otherwise, the history file will be overwritten.

**Comment by xavierchow** [comment]
sure, also make sure you remove or reword the file name of legacy History.md(e.g. History-obsoleted.md)

**Comment by superbogy** [comment]
It had been merged to master

**Comment by superbogy** [comment]
Seems that it works good for me. Issue close, reopen if there is any question. @xavierchow
