### ISSUE TITLE
The stale option in viewQuery should be able to set by custom setting

### ISSUE THREAD

**Issue by superbogy** [Wiredcraft/loopback-connector-couchbase3#114]
https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/09db6363a486b2a0904f5ce6012fe853d3b04274/lib/couchbaseX.js#L158

The `default value` should be:
```
const stale = this.settings.stale || ViewQuery.Update.NONE;
```
@xavierchow @makara

**Comment by xavierchow** [comment]
@superbogy it will be overridden by https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/09db6363a486b2a0904f5ce6012fe853d3b04274/lib/couchbaseX.js#L165-L169.

**Comment by xavierchow** [comment]
/remind me about this ticket in 17 hours.

**Comment by xavierchow** [comment]
oh, I see what you mean, you want a global default view setting from the `datasource setting`, I don't think it's necessary, varying the view query strategy through a project config might make a lot of confusion.

**Comment by superbogy** [comment]
resolve.
