### ISSUE TITLE
Make connector implement ping method

### ISSUE THREAD

**Issue by ChopperLee2011** [Wiredcraft/loopback-connector-couchbase3#28]
I want to use loopback datasource ping method to check the datasource status (died or not died), and i found this need call for the connector ping method, so should we add this method?
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L2135

**Comment by makara** [comment]
Sure. Grabbing.

**Comment by ChopperLee2011** [comment]
done.
