### ISSUE TITLE
odd null assignment

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-connector-couchbase3#4]
I have no idea about couchDB and juggle, but at a glance of code, I find this(https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/master/lib/couchbase3.js#L41-L43) is odd,
if no-strict equal null then set it as null? @makara

**Comment by dewey** [comment]
Good catch, the default password for couchbase buckets is an empty string so I guess it'd be more consistent to just assign an empty string there. I just pushed that change to #3 because I was dealing with that function there anyway.

**Comment by makara** [comment]
Thanks guys. I just didn't have time to dig.

**Comment by makara** [comment]
Fixed. Closing.
