### ISSUE TITLE
Error when _cas property is added to Loopback models after calling save()

### ISSUE THREAD

**Issue by sanagnos** [Wiredcraft/loopback-connector-couchbase3#78]
After updating a property of a Loopback model instance and calling `.save`, the following error is passed to the callback:

`ValidationError: The '<ModelName>' instance is not valid. Details: '_cas' is not defined in the model (value: undefined)`

This occurs when the Loopback model is configured with `strict` set to `true`, where `strict` "_specifies whether the model accepts only predefined properties or not._" ([source](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html))

Why is the check-and-set flag included as a property? And if so, is there an option to avoid this?

A workaround is to add a `_cas` property to the model's json spec.

Alternatively, there is no error & no need to change the model json spec if the following line is removed:
https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/master/lib/couchbase3.js#L397

**Comment by sanagnos** [comment]
This seems like a better fix, in-line with the `_type` property: https://github.com/Wiredcraft/loopback-connector-couchbase3/commit/99b7610b2e7df2367ae3134a913d886433efe2cd

**Comment by makara** [comment]
Well it's a feature Couchbase provides, so I'd like to give people a chance to use it, though I don't have a real use case, or maybe we can have an option? Also I guess adding a `_cas` doesn't hurt does it?

**Comment by sanagnos** [comment]
Fair enough, closing.
