### ISSUE TITLE
Add "example"

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-connector-couchbase3#8]
@WXGBridgeQ Please follow https://docs.strongloop.com/display/public/LB/Create+a+simple+API and add an example project in a folder `example`, switch the datasource from `db` to this project, add a random model (`Lorem` for example) and expose the REST API. Make sure `example` is in `.npmignore`. Please fork and send me a pull request. Ask @CCharlieLi if you have anything not sure.

**Comment by WXGBridgeQ** [comment]
@makara I'm working on it today, and stay with a problem about "How to load a custom connector into a loopback project". I find the answer at here https://groups.google.com/forum/#!topic/loopbackjs/wcDDYN6TiIE
I will try it again tomorrow.

**Comment by CCharlieLi** [comment]
@WXGBridgeQ 
There is my way. I digged deeply in `loopback-datasource-juggler` and find that we may need to modify the `datasource.js` source file to add our connector and then we can use it with just a short name like `couchbase`. I've not testing it and about to give it a try tomorrow.

- Add the short name `'couchbase'` at [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L201) in `connectorModuleNames` method, this method will generate a full name for connector like `loopback-connector-couchbase`.
- [Here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L214) is where the connector is loaded(or required), the `tryModules` method will return the connector instance. Maybe we can add a `if` branch in `tryModules` method to capture and load our connector.

**Comment by fraserxu** [comment]
> Add the short name 'couchbase' at here in connectorModuleNames method, this method will generate a full name for connector like loopback-connector-couchbase.

I believe it's not a good idea to modify the source code. 

@WXGBridgeQ You may use `slc loopback:datasource` to add a custom datasource(I name it couchbase3 here) to `./server/datasources.json`.

After that, you may also need to update the database connection configurations to something like 
```JavaScript
"couchbase": {
   "host": "192.168.75.144",
   "port": 8091,
   "connector": "couchbase3",
   "database": "lorem"
}
```

After that you could create a new model use our custom connector by running `slc loopabck:model` and select `couchbase3` as the datasource.

You can also user the connector in your code in the example directory directly like

```JavaScript
var DataSource = require('loopback-datasource-juggler').DataSource;
var dataSource = new DataSource(require('../index'), options);
```

After that you will be able to use it

```JavaScript
var Lorem = dataSource.createModel('lorem', {
    name: {type: String, id: true, required: true}
});
```

ref: 
* https://docs.strongloop.com/display/public/LB/Data+source+generator
* https://docs.strongloop.com/display/public/LB/PostgreSQL+connector
* https://github.com/dashby3000/loopback-connector-twilio/tree/master/example

**Comment by WXGBridgeQ** [comment]
@CCharlieLi  @fraserxu Thanks all! I will try out both way.

**Comment by CCharlieLi** [comment]
@fraserxu 
> I believe it's not a good idea to modify the source code. 

I agree. It is always not a good idea to change source file, but I don't think the custom connector could be recognized by just adding `"connector": "couchbase3"`.

@WXGBridgeQ I've tried my way and successfully connect and add a item in my local couchbase. And this is for test example only.
- This is my directory tree

![c4fde210-0bd0-467c-a92d-1c1f94ef549a](https://cloud.githubusercontent.com/assets/5690365/10444916/1d32bac2-719e-11e5-8b23-87f4a7de34b4.png)

- Use `slc loopback:datasource` to add a datasource `couchbase3`, run `slc loopabck:model` and select `couchbase3`, create your own model.
- Change the source file `loopback-connector-couchbase3/example/node_modules/loopback-datasource-juggler/lib/datasource.js`, simply add:
```
names.push('../../../../')
```
behind the [line 193](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L193), in this way our connector will always be found and loaded firstly.
- Make sure your local couchbase run at `127.0.0.1:8091`, and test `slc run`

BTW, I just find that `post` is ok but `get` and `put` method are not working properly, I'm working on it.

**Comment by fraserxu** [comment]
@CCharlieLi 
> but I don't think the custom connector could be recognized by just adding "connector": "couchbase3"

That I know and you are right :D , but I believe there must be a way to load it instead of modifying the code, maybe it will try to find it from `node_modules` and check if there's something like `loopback-connector-*` as I saw most of the 3rd party module doesn't have a way to load it from else where either. But they do require a `npm install`.

Maybe we can publish a alpha release to `npm` first and see whether it will work?

**Comment by WXGBridgeQ** [comment]
@CCharlieLi Thanks a lot. I try in this way, https://groups.google.com/forum/#!topic/loopbackjs/wcDDYN6TiIE
and also success to connect the couchbase.
The way is same to yours but the last step, I don't modify the source code of `loopback-datasource-juggler`, I've just add this line `app.connector('couchbase3', require('../connectors/couchbase3'));` to the `server/server.js`.

Thanks again.

**Comment by CCharlieLi** [comment]
Great!

**Comment by fraserxu** [comment]
:+1:

**Comment by fraserxu** [comment]
So I presume adding `app.connector('couchbase3', require('loopback-connector-couchbase3')` to `server/server.js` is the correct way to do it?

**Comment by WXGBridgeQ** [comment]
Yes, it looks better. But it can't find in the official documents.

**Comment by CCharlieLi** [comment]
Seems the easiest way to add a custom connector, how to config a datasource then? so it can be recognized now?
```
"couchbase": {
   "host": "127.0.0.1",
   "port": 8091,
   "connector": "couchbase3"
}
```

**Comment by WXGBridgeQ** [comment]
in my `datasources.json`
```
"couchbase3Ds": {
    "name": "couchbase3Ds",
    "connector": "couchbase3",
    "host": "localhost",
    "port": 8091,
    "database": "default"
  }
```

**Comment by fraserxu** [comment]
@CCharlieLi add `app.connector('couchbase3', require('loopback-connector-couchbase3'))` to `server/server.js` in the app.

**Comment by WXGBridgeQ** [comment]
👍

**Comment by makara** [comment]
I actually prefer `'../connectors/couchbase3'` cause we are adding an example **in** the project, not outside, but up to you. Also, can we use `couchbase` as the connector name instead of `couchbase3`? I use `couchbase3` cause it's the version 3 but logically speaking the DB name is `couchbase`.

**Comment by WXGBridgeQ** [comment]
ok, I will use `../connectors/couchbase`.
the last version of couchbase is 4 now 😃

**Comment by makara** [comment]
Yeah but we are building a connector for 3.

**Comment by WXGBridgeQ** [comment]
@CCharlieLi I also find the GET API response with 500, error message is 'First argument needs to be a string or buffer.'
I really don't know the reason, the methods we support isn't enough? Can you help with this?

**Comment by CCharlieLi** [comment]
@WXGBridgeQ 
Yes, as I metioned the `post` seems ok but `get` and `put` method are not working properly, I'm working on it.

**Comment by makara** [comment]
Thanks. Closing.
