### ISSUE TITLE
Confusion about not found case of `findById`

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-connector-couchbase3#86]
I'm wondering what's the best approach for not found case of `findById`,
1. return null
2. throw error,

From the current implementation, it always returns null even there is a `throw clause` 
https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/76cad19efb0d464fdff435143a061f0213553a5a/lib/couchbase3.js#L335-L340
the reason is that the `unpack` resolves with null if `data` is null, so the 404 error will never be thrown.
https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/76cad19efb0d464fdff435143a061f0213553a5a/lib/couchbase3.js#L387-L391

I'm fine with both approaches but I don't think 404 is appropriate coz it's the application which uses this library should care and define the error code.

@makara @CCharlieLi

**Comment by makara** [comment]
- 404 is just a convention. You can define a different code but it's the same thing - the app needs to translate in the end.
- Typically "find by something" would return a list, and if not found, an empty list, but I consider "find by ID" a special case cause it's usually used with loading a resource, and if you think in the RESTful way if a resource is not there it throws, but again, it's a convention.

**Comment by CCharlieLi** [comment]
I agree to return null as it is what from couchbase instead of return 404. 
Not sure why there's a `httpError`, it looks like legacy code that has not been declared anywhere.

**Comment by xavierchow** [comment]
It seems the `data == null` check doesn't work at all coz it throws the following error before entering the `then` resolver.
> CouchbaseError: The key does not exist on the server

**Comment by pivstone** [comment]
I suggest this apporach:  `findById(id, raise_exception = false)` or `findById(id, err_clz = NotFoundException)` . Let the user choose which one.

In my practice, I like `findById` throw 404 instead of check if it's null then throw a 404 in most case. But in some cases, I still need to do some things (revert transaction or logging) before I throw 401 or 404 to frontend.

**Comment by xavierchow** [comment]
>  I like findById throw 404 instead of check if it's null then throw a 404 in most case. 

I believe this is the loopback default way, but the loopback-connector-nosql just hides the error.
https://github.com/Wiredcraft/loopback-connector-nosql/blob/0b26618f03b54a038c31400a57d52f4bbf54b11e/lib/nosql.js#L370-L372

The flow is as below,
`model.findById` -> [Juggler findById](https://github.com/strongloop/loopback-datasource-juggler/blob/507621c370ad6c2a6472c58678c01fe45b2e927e/lib/dao.js#L1310)  -> [Juggler findOne](https://github.com/strongloop/loopback-datasource-juggler/blob/507621c370ad6c2a6472c58678c01fe45b2e927e/lib/dao.js#L1755) -> `findAll with limit 1` 
-> [nosql findByIds](https://github.com/Wiredcraft/loopback-connector-nosql/blob/master/lib/nosql.js#L361), but here the `catchReturn` and `filter(Boolean)` filters the result to null.

Maybe we should let jugger calls `findById` directly for nosql connector, but I don't have time to investigate it now.

**Comment by xavierchow** [comment]
Returning null form 1.0.0, closing.
