### ISSUE TITLE
Support for filtering nested properties

### ISSUE THREAD

**Issue by Elethom** [Wiredcraft/loopback-connector-couchbase3#87]
https://loopback.io/doc/en/lb3/Querying-data.html#filtering-nested-properties

**Comment by xavierchow** [comment]
Nice to have, but not a high priority, we can always have view query for nested property search.
@pivstone I guess we still need to create GSI if using N1QL, right?

**Comment by pivstone** [comment]
N1QL needs one of them:
- Primary Index
- GSI

And we have https://github.com/Wiredcraft/loopback-n1ql-mixin , so we don't need to support it at the connector.

**Comment by xavierchow** [comment]
it's out of the scope of this npm, closing.
