### ISSUE TITLE
Default stale param of view query

### ISSUE THREAD

**Issue by xavierchow** [Wiredcraft/loopback-connector-couchbase3#88]
https://docs.couchbase.com/server/4.1/indexes/mapreduce-view-consistency.html.

Current implementation set stale = false as default which is not the default value of doc of CB(update_after).
https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/76cad19efb0d464fdff435143a061f0213553a5a/lib/couchbase3.js#L151

This causes our developers to have a feeling(misunderstanding) that the view always return the latest data but actually, the re-index might be a heavy operation on DB and cause the obvious latency.

I suggest `loopback-connector-couchbase3` changes the default to `udpate_afeter` just the same as the default of the CB doc.

**Comment by xavierchow** [comment]
cc @Wiredcraft/wiredcraft-backend-team

**Comment by CCharlieLi** [comment]
The default setting of couchbase.js is [Update.NONE`](https://docs.couchbase.com/sdk-api/couchbase-node-client-2.1.4/ViewQuery.html#stale) means allows the index to stay in whatever state it is already in prior retrieval of the query results.

I agree to remove `.stale(ViewQuery.Update.BEFORE);` from connector as it may potentially cause perf issue. **Neither should we use `udpate_afeter`**, it has no difference on perf issue as it forces couchbase to re-index after each query.

Developers should be aware of this and handle it separately.

**Comment by xavierchow** [comment]
@CCharlieLi are we checking different docs?
>update_after
This is the default value used when the stale parameter is not specified. The views engine uses the existing index as the basis of the query and marks the index to be updated after the results are returned to the client.

Each param should be well considered according to different scenarios, there is always a place to apply them, e.g. `update_after` is good if you expect a short latency but still want a relative fresh data for next query.

**Comment by CCharlieLi** [comment]
@xavierchow I'm sure we are both using connector in LB, connector is using couchbase.js, and couchbase is using ViewQuery.Update.NONE https://docs.couchbase.com/sdk-api/couchbase-node-client-2.1.4/ViewQuery.html#stale as default value.

> Each param should be well considered according to different scenarios, there is always a place to apply them.

That's also what I meant. Couchbase has it's own logic to update and re index, it's not necessary to use `update_after` to force re index after **each** query. Again `Each param should be well considered according to different scenarios`.

**Comment by haishanh** [comment]
Agree to set default view update to NONE

But we need to make sure the team know they understand what does this means and have options to set it to  BEFORE and AFTER

https://github.com/couchbase/couchnode/blob/v2.6.6/lib/viewquery.js#L30-L47

**Comment by xavierchow** [comment]
Ok, it seems we are all aligned @CCharlieLi could you help to send a PR?

**Comment by CCharlieLi** [comment]
Will do. Thanks both.

**Comment by haishanh** [comment]
(This is a breaking change, we will need to bump up the major version, also need to broadcast team members)

**Comment by CCharlieLi** [comment]
Yes it's a kinda breaking change, even both @zbal and me think that we may keep stale param there to reindex before query:

- after we've used it for long time, there's no common critical issue cause by that.
- this change will require all components that are using connector to check and update their logic accordingly.
- default stale can be easily covered with given params if it's CB perf sensitive.

@xavierchow

**Comment by xavierchow** [comment]
Yes, it's been there for a long time but it does cause issues(critical if massive data in CB), my concern here is more about explicit, current default as `BEFORE` is not consistent with the official document of CB or spec of CB SDK, nor it's well-known by some of the developers. (so ppl might abuse without awareness)
This was the wrong decision to change the default stale but without documentation as an open-source library(or a widely used library in our internal system)
We can fix it with a major version change(v1.x.x), which means the existing callers can still work with the current major version(v0.x.x) unless they decide to upgrade.

**Comment by CCharlieLi** [comment]
that makes sense, thanks

**Comment by xavierchow** [comment]
landed in 1.0.0, closing.
