### ISSUE TITLE
Review CRUD

### ISSUE THREAD

**Issue by makara** [Wiredcraft/loopback-connector-couchbase3#9]
@ChopperLee2011 Please review what we have now.

I see something strange for example, that the implemented hooks are very different with the other official connectors, like https://github.com/strongloop/loopback-connector-redis/blob/master/lib/redis.js.

Please talk with @CCharlieLi .

**Comment by ChopperLee2011** [comment]
i create a new branch  module-uuid (https://github.com/Wiredcraft/loopback-connector-couchbase3/tree/module-uuid)  with the list points:
- add uuid for module when create or update method do not have one.
- the lib code seem wrap up all the thing to promise, but the test still use callback. And also kind of not have a clean view.

**Comment by makara** [comment]
So is it ready to release? Did you test it in any other projects we are working on?

**Comment by ChopperLee2011** [comment]
@makara  use it in the ams project, seem still need other feature, and #11 is the most needed feature as a use (me) , the exists api passed the test but not cover all in our project right now

**Comment by makara** [comment]
Can you send me a pull request when you think it's ready.

**Comment by makara** [comment]
Can you also build a benchmark test.

**Comment by makara** [comment]
Sending to @CCharlieLi .

@CCharlieLi, I implemented a few more connector methods. Please add test for all of them:

- Figure our how a model instance invoke each of the methods and test each of them.
- Put the tests for each method in a separate describe().

**Comment by CCharlieLi** [comment]
Yes, on it.

**Comment by CCharlieLi** [comment]
Methods hook in DataAccessObject. FYI.

- *idName(model)   //get id name from model
- *getIdValue(m, data) 
//get id value
- *setIdValue(m, data, value) 
//set id by giving value
- *byIdQuery(m, id) 
//generate query by giving id
- *isWhereByGivenId(Model, where, idValue) 
// if it's `where` of giving id
- *getConnector() 
// get Connector instance
- *create(data, options, cb) -> __connector.create__
// Create an instance of Model with given data and save to the attached data source.
- updateOrCreate/upsert(data, options, cb) ->  __connector.updateOrCreate__/__connector.findOne__-__updateAttributes__
// Update or insert a model instance
- findOrCreate(query, data, options, cb) ->  __connector.findOrCreate__/ findOne - __connector.create__
//Find one record or create it using data provided
- exists(id, options, cb) -> __connector.count__
//Check whether a model instance exists in database
- *findById(id, filter, options, cb) -> findOne
//Find model instance by ID.
- *findByIds(ids, query, options, cb) 
//Find model instances by ids -> find
- all() -> find
//alias function for backwards compat.
- *find(query, options, cb) -> __connector.all__
//Find all instances of Model that match the specified query.
- findOne(query, options, cb) -> find
//Find one record
- *remove/deleteAll/destroyAll(where, options, cb) -> __connector.destroyAll__
//Destroy all matching records.
- *removeById/destroyById/deleteById(id, options, cb) -> remove
//Delete the record with the specified ID.
- count(where, options, cb) -> __connector.count__
//Return count of matched records.
- save(options, cb) -> __connector.save__
//Save instance.
- *update/updateAll(where, data, options, cb) -> __connector.update__
//Update multiple instances that match the where clause 
- remove/delete/destroy -> Model.deleteAll/connector.destroy
//Delete object from persistence

**Comment by CCharlieLi** [comment]
Done, closing.
