### ISSUE TITLE
[Bug] findAll always return staled data

### ISSUE THREAD

**Issue by CCharlieLi** [Wiredcraft/loopback-connector-couchbase3#99]
We have removed default `pre-index` option for queryview and we'd like the option to be passed to Couchbase by each use case.

https://github.com/Wiredcraft/loopback-connector-couchbase3/blob/417994033fce5805fca207a110ec317a36e722f7/lib/couchbaseX.js#L365-L367

As `findAll` is actually using queryview to fetch data without giving any stale option, currently it's always returning staled data, thanks @wwayne for reporting this issue. 

Ideally we can use `findAll(options)` to achieve that.

**Comment by xavierchow** [comment]
addressed in https://github.com/Wiredcraft/loopback-connector-couchbase3/pull/102/files#diff-afa091a9bb8da3eaff5c46270d3ed166R367-R368.

**Comment by xavierchow** [comment]
Landed in v1.2.0, closing.
